require("lazy").setup({
  {
    "nvim-treesitter/nvim-treesitter-context",
    config = function()
      vim.keymap.set("n", "<leader>ct", "<cmd>TSContextToggle<cr>", { desc = "[C]ontext toggle" })
      vim.keymap.set("n", "[c", function()
        require("treesitter-context").go_to_context(vim.v.count1)
      end, { silent = true })
    end,
  },
  { "numToStr/Comment.nvim", opts = {} },
  "famiu/bufdelete.nvim",
  require("plugins.ts-autotag"),
  require("plugins.satellite"),
  require("plugins.zen-mode"),
  require("plugins.auto-save"),
  require("plugins.lualine"),
  require("plugins.lazygit"),
  require("plugins.smart-splits"),
  require("plugins.grapple"),
  require("plugins.dressing"),
  require("plugins.toggleterm"),
  require("plugins.ufo"),
  require("plugins.window-picker"),
  require("plugins.neo-tree"),
  require("plugins.suda"),
  require("plugins.nvim-lint"),
  require("plugins.Navigator"),
  require("plugins.undotree"),
  require("plugins.nvim-dap-ui"),
  require("plugins.leap"),
  require("plugins.flit"),
  require("plugins.gitsigns"),
  require("plugins.which-key"),
  require("plugins.telescope"),
  require("plugins.lspconfig"),
  require("plugins.conform"),
  require("plugins.cmp"),
  require("plugins.tokyonight"),
  require("plugins.todo-comments"),
  require("plugins.mini"),
  require("plugins.treesitter"),
}, {
  ui = {
    icons = vim.g.have_nerd_font and {} or {
      cmd = "⌘",
      config = "🛠",
      event = "📅",
      ft = "📂",
      init = "⚙",
      keys = "🗝",
      plugin = "🔌",
      runtime = "💻",
      require = "🌙",
      source = "📄",
      start = "🚀",
      task = "📌",
      lazy = "💤 ",
    },
  },
})
